### ISSUE TITLE
Localizer for Packaged app

### ISSUE THREAD

**Issue by ghost1372** [AndrewKeepCoding/AK.Toolkit#16]
in packaged app we can access resources like this:

`var xx = new ResourceManager().MainResourceMap.GetValue("Files/MyFile.ext")`
so we can use this code with a little optimization for support packaged and unpackaged app.

**Comment by AndrewKeepCoding** [comment]
Sorry I don't follow. Do you mean that we won't need the path for the resources?

**Comment by ghost1372** [comment]
in this case we can find resources but we cant edit theme like in unpackaged. we just can read values based on our language tag.
give me more time im working on it...

**Comment by AndrewKeepCoding** [comment]
But as far as I know, you can't edit those *.pri files right? That would be dropping the availability for editing/adding  localized strings even after deployment, which is one of the main reason why I created this🤔

**Comment by ghost1372** [comment]
yes we can only read them. I'm still looking for better ways to do this but haven't found anything good yet

**Comment by AndrewKeepCoding** [comment]
Closed by #24
