### ISSUE TITLE
AutoCompleteTextBox does not show suggestion on Light mode

### ISSUE THREAD

**Issue by AndrewKeepCoding** [AndrewKeepCoding/AK.Toolkit#3]
Since it shows the suggestion when the ``Background`` is set to ``Transparent``, this seems to be related to the default style  ``Background``, which is ``ThemeResource TextControlBackground``.

**Comment by AndrewKeepCoding** [comment]
Tried to make the original make the ``Background`` transparent and overlap the input text, but there are cases when the typed input text render is different from programmatically input text. ([see this question at StackOverflow](https://stackoverflow.com/questions/72031365/why-the-text-rendering-is-different-between-default-text-and-user-typed-text/72037601#72037601))

![image](https://user-images.githubusercontent.com/80524586/165761401-ad3a299e-8299-4ef1-87e7-fc11ee007ed7.png)

**Comment by ghost1372** [comment]
Ok, so the last way is to retemplate the TextBox

**Comment by AndrewKeepCoding** [comment]
Hi @ghost1372 ! I was retemplating the TextBox but ending up editing just a few lines of the entire default style. And this is why I try to avoid touching the default style.
This merge fixes both, the Light mode problem and the IME problem.
Can you take a look? I'd really appreciate it.😊

**Comment by ghost1372** [comment]
Hi @AndrewKeepCoding 
Tnx for fixing issues
Everything works fine

**Comment by AndrewKeepCoding** [comment]
Thank you @ghost1372 !👍
