### ISSUE TITLE
New annotations artifact

### ISSUE THREAD

**Issue by GuildOfCalamity** [AndrewKeepCoding/AK.Toolkit#42]
I noticed there are scenarios where the annotations live outside the control...

![image](https://user-images.githubusercontent.com/81915293/229296267-3e84c658-f94a-420d-a5d9-13392e4c852b.png)

**UPDATE:** It only seems to happen after enabling the **KeepExpanded** options from another sample tab.

**Comment by AndrewKeepCoding** [comment]
@GuildOfCalamity Thanks for the feedback. I was able to reproduce this issue. This happens when navigating back to "Annotations" page. I think I can fix this tommorrow.

**Comment by AndrewKeepCoding** [comment]
It was a problem in the sample app. Thanks again for the feedback.
