### ISSUE TITLE
ScrollBarExtensions: Scrollbar looses 'expanded' display mode on page reload

### ISSUE THREAD

**Issue by MartinFraAtGitHub** [AndrewKeepCoding/AK.Toolkit#44]
I have a DataGrid inside a page.
I have set the "KeepHorizontalExpanded" and "KeepVerticalExpanded" properties in a style for the "DataGrid" type that is used application wide, see code below.

When the page is loaded initially the "expanded" settings for the scrollbars work.
But when I navigate to another page and then return to the previous page the "expanded" settings are no longer applied.

I notice the problem also when I have a "TabView" with "TabViewItem"s. On a TabViewItem instance "A" I have a DataGrid with the expanded scrollbars set. This is displayed correctly the first time the respective TabViewItem "A" loads. But when I nagivate to another TabViewItem "B" and then back to the first one "A", the scrollbars in the DataGrid are no longer displayed in "expanded" mode.

This file "DataGrid.xaml" file is included in the applications "App.xaml" defintion:

<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:akToolkitWinUi3="using:AK.Toolkit.WinUI3"
    xmlns:controls="using:CommunityToolkit.WinUI.UI.Controls">

    <ResourceDictionary.MergedDictionaries>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </ResourceDictionary.MergedDictionaries>

    <Style TargetType="controls:DataGrid">

        
        
        <Setter Property="akToolkitWinUi3:ScrollBarExtensions.KeepHorizontalExpanded" Value="true"/>
        <Setter Property="akToolkitWinUi3:ScrollBarExtensions.KeepVerticalExpanded" Value="true"/>

    </Style>

</ResourceDictionary>

**Comment by AndrewKeepCoding** [comment]
Thanks for the feedback @MartinFraAtGitHub!

This happens when the target control , a ``DataGrid`` in this case, is unloaded but cashed so when you navigate back the cashed control is reused.

I think I can make some time and fix this in the next few days.

**Comment by AndrewKeepCoding** [comment]
Thanks again for the feedback @MartinFraAtGitHub!

**Comment by MartinFraAtGitHub** [comment]
I can confirm that this problem is fixed in version 1.0.5.
Thank you :)
