### ISSUE TITLE
NumberBox min width. 

### ISSUE THREAD

**Issue by Petrarca181** [AndrewKeepCoding/AK.Toolkit#52]
How I need numerbox  for 2 digit numbers. I need a small one like Witdh="30".  But  If go under Witdh="70" textbox/nuberbox just  cuts itself, I removed clear button, but still can't make it smaller . There is any way to fix this? Thank you.  

![image](https://github.com/AndrewKeepCoding/AK.Toolkit/assets/54235138/83da7a02-3855-4e51-b003-10daaa463223)

**Comment by AndrewKeepCoding** [comment]
@Petrarca181 Thanks for the feedback! This is fixed on v1.0.1.😉

**Comment by AndrewKeepCoding** [comment]
Have you tried the setting the `MinWidth`?
